<?php

declare(strict_types=1);

namespace MageOS\Seo\Model\Hreflang;

use Magento\Framework\App\ResourceConnection;

/**
 * Reads canonical URL rewrites from the url_rewrite table for hreflang resolution.
 *
 * Only autogenerated, non-redirect rows are used, so each store maps to its current canonical
 * request path. Stores where an entity has no rewrite (e.g. not assigned to that store) are simply
 * absent — which is exactly the correct hreflang behaviour.
 */
class UrlRewriteFetcher
{
    /**
     * @param ResourceConnection $resourceConnection
     */
    public function __construct(
        private readonly ResourceConnection $resourceConnection
    ) {
    }

    /**
     * Fetch canonical request paths for one entity, keyed by store ID.
     *
     * @param string $entityType 'product' | 'category' | 'cms-page'
     * @param int $entityId
     * @return array<int, string> store_id => request_path
     */
    public function fetchForEntity(string $entityType, int $entityId): array
    {
        $connection = $this->resourceConnection->getConnection();
        $table      = $this->resourceConnection->getTableName('url_rewrite');

        $rows = $connection->fetchAll(
            $connection->select()
                ->from($table, ['store_id', 'request_path'])
                ->where('entity_type = ?', $entityType)
                ->where('entity_id = ?', $entityId)
                ->where('redirect_type = ?', 0)
                ->where('is_autogenerated = ?', 1)
                // Product rows with metadata carry a category context (category-nested
                // URLs); hreflang alternates must point at the canonical root rewrite.
                ->where('metadata IS NULL')
                ->order('url_rewrite_id ASC')
        );

        $paths = [];
        foreach ($rows as $row) {
            $storeId = (int) $row['store_id'];
            // First canonical row per store wins; ordering makes the winner deterministic.
            if (!isset($paths[$storeId])) {
                $paths[$storeId] = (string) $row['request_path'];
            }
        }

        return $paths;
    }

    /**
     * Stream canonical request paths for every entity of a type, one entity at a time.
     *
     * One query for the whole catalogue, walked row by row and grouped on entity_id, so the
     * sitemap generator never holds every rewrite of every store view at once.
     *
     * @param string $entityType
     * @param int[] $storeIds
     * @return \Generator<int, array<int, string>> store_id => request_path, per entity
     */
    public function streamAllForType(string $entityType, array $storeIds): \Generator
    {
        if ($storeIds === []) {
            return;
        }

        $connection = $this->resourceConnection->getConnection();
        $table      = $this->resourceConnection->getTableName('url_rewrite');

        $statement = $connection->query(
            $connection->select()
                ->from($table, ['entity_id', 'store_id', 'request_path'])
                ->where('entity_type = ?', $entityType)
                ->where('store_id IN (?)', $storeIds)
                ->where('redirect_type = ?', 0)
                ->where('is_autogenerated = ?', 1)
                // Root rewrites only: excludes category-nested product URL variants,
                // which both bloats the result set and picks non-canonical URLs.
                ->where('metadata IS NULL')
                // Grouping happens on consecutive rows, so entity_id leads the ordering;
                // url_rewrite_id keeps the winner per store deterministic.
                ->order('entity_id ASC')
                ->order('url_rewrite_id ASC')
        );

        $currentEntityId = null;
        $paths           = [];

        while ($row = $statement->fetch()) {
            $entityId = (int) $row['entity_id'];
            if ($currentEntityId !== null && $entityId !== $currentEntityId) {
                yield $paths;
                $paths = [];
            }
            $currentEntityId = $entityId;

            $storeId = (int) $row['store_id'];
            // First canonical row per store wins; ordering makes the winner deterministic.
            if (!isset($paths[$storeId])) {
                $paths[$storeId] = (string) $row['request_path'];
            }
        }

        if ($paths !== []) {
            yield $paths;
        }
    }
}
