<?php

declare(strict_types=1);

namespace MageOS\Seo\Model\Hreflang;

use MageOS\Seo\Model\ResourceModel\UrlRewrite as UrlRewriteResource;

/**
 * Reads canonical URL rewrites from the url_rewrite table for hreflang resolution.
 *
 * Only autogenerated, non-redirect rows of published entities are used, so each store maps to its
 * current canonical request path. Stores where an entity has no rewrite (e.g. not assigned to that
 * store), and entities a visitor cannot reach (disabled products, inactive categories, unpublished
 * CMS pages), are simply absent — which is exactly the correct hreflang behaviour.
 *
 * The queries themselves live in the resource model; this class turns their rows into the shape
 * the sitemap and the head links want.
 */
class UrlRewriteFetcher
{
    /**
     * @param UrlRewriteResource $urlRewriteResource
     */
    public function __construct(
        private readonly UrlRewriteResource $urlRewriteResource
    ) {
    }

    /**
     * Fetch canonical request paths for one entity, keyed by store ID.
     *
     * @param string $entityType 'product' | 'category' | 'cms-page'
     * @param int $entityId
     * @return array<int, string> store_id => request_path
     */
    public function fetchForEntity(string $entityType, int $entityId): array
    {
        $paths = [];
        foreach ($this->urlRewriteResource->getPathsForEntity($entityType, $entityId) as $row) {
            $storeId = (int) $row['store_id'];
            // First canonical row per store wins; ordering makes the winner deterministic.
            if (!isset($paths[$storeId])) {
                $paths[$storeId] = (string) $row['request_path'];
            }
        }

        return $paths;
    }

    /**
     * Stream canonical request paths for every entity of a type, one entity at a time.
     *
     * One query for the whole catalogue, walked row by row and grouped on entity_id, so the
     * sitemap generator never holds every rewrite of every store view at once.
     *
     * @param string $entityType
     * @param int[] $storeIds
     * @return \Generator<int, array<int, string>> store_id => request_path, per entity
     */
    public function streamAllForType(string $entityType, array $storeIds): \Generator
    {
        if ($storeIds === []) {
            return;
        }

        $statement = $this->urlRewriteResource->queryPathsForType($entityType, $storeIds);

        $currentEntityId = null;
        $paths           = [];

        while ($row = $statement->fetch()) {
            $entityId = (int) $row['entity_id'];
            if ($currentEntityId !== null && $entityId !== $currentEntityId) {
                yield $paths;
                $paths = [];
            }
            $currentEntityId = $entityId;

            $storeId = (int) $row['store_id'];
            // First canonical row per store wins; ordering makes the winner deterministic.
            if (!isset($paths[$storeId])) {
                $paths[$storeId] = (string) $row['request_path'];
            }
        }

        if ($paths !== []) {
            yield $paths;
        }
    }
}
