<?php

declare(strict_types=1);

namespace MageOS\Seo\Model\Hreflang;

use MageOS\Seo\Model\ResourceModel\UrlRewrite as UrlRewriteResource;

/**
 * Reads canonical URL rewrites from the url_rewrite table for hreflang resolution.
 *
 * Only autogenerated, non-redirect rows of published entities are used, so each store maps to its
 * current canonical request path. Stores where an entity has no rewrite (e.g. not assigned to that
 * store), and entities a visitor cannot reach (disabled products, inactive categories, unpublished
 * CMS pages), are simply absent — which is exactly the correct hreflang behaviour.
 *
 * The queries themselves live in the resource model; this class turns their rows into the shape
 * the sitemap and the head links want.
 */
class UrlRewriteFetcher
{
    /**
     * @param UrlRewriteResource $urlRewriteResource
     */
    public function __construct(
        private readonly UrlRewriteResource $urlRewriteResource
    ) {
    }

    /**
     * Fetch canonical request paths for one entity, keyed by store ID.
     *
     * @param string $entityType 'product' | 'category' | 'cms-page'
     * @param int $entityId
     * @return array<int, string> store_id => request_path
     */
    public function fetchForEntity(string $entityType, int $entityId): array
    {
        return $this->firstPathPerStore($this->urlRewriteResource->getPathsForEntity($entityType, $entityId));
    }

    /**
     * Fetch the request paths of a CMS translation group, keyed by store ID.
     *
     * Each store view maps to its own translation — the page assigned to it, else one assigned to
     * all store views, the lowest page ID breaking a tie.
     *
     * @param string $group A normalised translation group
     * @return array<int, string> store_id => request_path
     */
    public function fetchForCmsGroup(string $group): array
    {
        return $this->firstPathPerStore($this->urlRewriteResource->getPathsForCmsGroup($group));
    }

    /**
     * Fetch canonical request paths for several entities of one type, in one query.
     *
     * @param string $entityType
     * @param int[] $entityIds
     * @return array<int,array<int,string>> entity_id => (store_id => request_path); entities without
     *                                      a published rewrite are absent
     */
    public function fetchForEntities(string $entityType, array $entityIds): array
    {
        $rows  = $this->urlRewriteResource->getPathsForEntities($entityType, $entityIds);
        $paths = [];
        foreach ($this->perKey($rows, 'entity_id') as $id => $storePaths) {
            $paths[(int) $id] = $storePaths;
        }

        return $paths;
    }

    /**
     * Fetch the request paths of several CMS translation groups, in one query.
     *
     * @param string[] $groups Normalised translation groups
     * @return array<int|string,array<int,string>> group => (store_id => request_path); PHP makes a
     *                                            group of digits, such as "404", an integer key
     */
    public function fetchForCmsGroups(array $groups): array
    {
        return $this->perKey($this->urlRewriteResource->getPathsForCmsGroups($groups), 'hreflang_group');
    }

    /**
     * Split rows by a column, and reduce each set to one request path per store view.
     *
     * @param array<int,array<string,mixed>> $rows
     * @param string $column
     * @return array<int|string,array<int,string>>
     */
    private function perKey(array $rows, string $column): array
    {
        $byKey = [];
        foreach ($rows as $row) {
            $byKey[$row[$column]][] = $row;
        }

        return array_map(fn (array $keyRows): array => $this->firstPathPerStore($keyRows), $byKey);
    }

    /**
     * Stream canonical request paths for every entity of a type, one entity at a time.
     *
     * One query for the whole catalogue, walked row by row and grouped on the row's group key, so
     * the sitemap generator never holds every rewrite of every store view at once. The key is the
     * entity itself, except for CMS pages in a translation group, which come out as one entity.
     *
     * @param string $entityType
     * @param int[] $storeIds
     * @return \Generator<int, array<int, string>> store_id => request_path, per entity
     */
    public function streamAllForType(string $entityType, array $storeIds): \Generator
    {
        if ($storeIds === []) {
            return;
        }

        $statement = $this->urlRewriteResource->queryPathsForType($entityType, $storeIds);

        $currentKey = null;
        $rows       = [];

        while ($row = $statement->fetch()) {
            $key = (string) $row['group_key'];
            if ($currentKey !== null && $key !== $currentKey) {
                yield $this->firstPathPerStore($rows);
                $rows = [];
            }
            $currentKey = $key;
            $rows[]     = $row;
        }

        if ($rows !== []) {
            yield $this->firstPathPerStore($rows);
        }
    }

    /**
     * Reduce rewrite rows to one request path per store view: the first row's.
     *
     * The queries order their rows so the first per store is the one to use.
     *
     * @param iterable<array<string,mixed>> $rows
     * @return array<int, string> store_id => request_path
     */
    private function firstPathPerStore(iterable $rows): array
    {
        $paths = [];
        foreach ($rows as $row) {
            $storeId = (int) $row['store_id'];
            if (!isset($paths[$storeId])) {
                $paths[$storeId] = (string) $row['request_path'];
            }
        }

        return $paths;
    }
}
