<?php

declare(strict_types=1);

namespace MageOS\Seo\Console\Command;

use Magento\Framework\App\Area;
use Magento\Framework\App\State;
use Magento\Framework\Exception\LocalizedException;
use MageOS\Seo\Exception\FeedRebuildInProgressException;
use MageOS\Seo\Exception\SitemapRebuildInProgressException;
use MageOS\Seo\Model\Feed\FeedRegenerator;
use MageOS\Seo\Model\Sitemap\RebuildableSitemaps;
use MageOS\Seo\Model\Sitemap\Rebuilder as SitemapRebuilder;
use MageOS\Seo\Model\Sitemap\RebuildGroup;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Rebuilds the pre-generated SEO feeds immediately, in this process — or, asked by group, one type
 * of page in the XML sitemaps this module generates.
 *
 * The manual counterpart of the nightly cron and the queue: for deployment scripts that need the
 * feeds in place before traffic arrives, and for rebuilding on demand — a sitemap type after a
 * change the rebuild-on-change triggers cannot see, such as an import written straight to the
 * database. It does not need the queue consumer to be running. With no group it rebuilds the
 * feeds only: a sitemap is rebuilt when a `sitemap-…` group is named.
 */
class RegenerateFeedsCommand extends Command
{
    private const OPTION_GROUP = 'group';

    /**
     * @param FeedRegenerator $feedRegenerator Injected as a proxy: builders load only when the command runs
     * @param State $appState
     * @param SitemapRebuilder $sitemapRebuilder Injected as a proxy, for the same reason
     * @param RebuildableSitemaps $rebuildableSitemaps
     * @param RebuildGroup $rebuildGroup
     * @param string|null $name
     */
    public function __construct(
        private readonly FeedRegenerator     $feedRegenerator,
        private readonly State               $appState,
        private readonly SitemapRebuilder    $sitemapRebuilder,
        private readonly RebuildableSitemaps $rebuildableSitemaps,
        private readonly RebuildGroup        $rebuildGroup,
        ?string $name = null
    ) {
        parent::__construct($name);
    }

    /**
     * @inheritDoc
     */
    protected function configure(): void
    {
        $this->setName('mageos:seo:feeds:regenerate')
            ->setDescription(
                'Rebuild the SEO feeds (llms.txt, llms-full.txt, llms.jsonl) for every active store view,'
                . ' or a type of page in the XML sitemaps'
            )
            ->addOption(
                self::OPTION_GROUP,
                'g',
                InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY,
                'Group to rebuild: a feed (' . implode(', ', FeedRegenerator::GROUPS) . '); '
                . RebuildGroup::PREFIX . 'TYPE for one type of page in every sitemap generated by MageOS SEO'
                . ' (' . RebuildGroup::PREFIX . 'pages, ' . RebuildGroup::PREFIX . 'products, or another'
                . ' module\'s type); or \'' . RebuildGroup::PREFIX . RebuildGroup::ALL_TYPES . '\' for every type.'
                . ' Repeat for several. Default: every feed, no sitemap'
            );

        parent::configure();
    }

    /**
     * @inheritDoc
     */
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $groups  = array_values(array_unique(array_map('strval', (array) $input->getOption(self::OPTION_GROUP))));
        $unknown = array_values(array_filter($groups, fn (string $group): bool => !$this->isKnown($group)));
        if ($unknown !== []) {
            $output->writeln(\sprintf(
                '<error>Unknown feed group(s): %s. Use: %s.</error>',
                implode(', ', $unknown),
                implode(', ', $this->knownGroups())
            ));
            return Command::INVALID;
        }

        $failures = [];
        try {
            $this->ensureAreaCode();
            foreach ($groups === [] ? [null] : $groups as $group) {
                $label = $group ?? 'all feeds';
                $output->writeln(\sprintf('Rebuilding %s...', $label));

                $sitemapType = $group === null ? null : $this->rebuildGroup->typeOf($group);
                if ($sitemapType === null) {
                    foreach ($this->feedRegenerator->regenerate($group) as $storeId => $message) {
                        $failures[] = \sprintf('%s, store view %d: %s', $label, $storeId, $message);
                    }
                    continue;
                }

                if ($this->rebuildableSitemaps->all() === []) {
                    $output->writeln(
                        '<comment>No sitemap to rebuild: none has been generated on an active store view'
                        . ' that uses the MageOS SEO generator. Generate one under Marketing → Site Map.</comment>'
                    );
                    continue;
                }
                foreach ($this->sitemapRebuilder->rebuildOnDemand($sitemapType) as $sitemapId => $message) {
                    $failures[] = \sprintf('%s, sitemap %d: %s', $label, $sitemapId, $message);
                }
            }
        } catch (FeedRebuildInProgressException | SitemapRebuildInProgressException $e) {
            // Distinguished from a crash for the operator's sake — nothing is broken, the cron or
            // the queue consumer is mid-rebuild. Still a failure: the files asked for were not
            // written, and a deployment script must not read this as "done".
            $output->writeln('<error>' . $e->getMessage() . '</error>');
            $output->writeln('<comment>Wait for the running rebuild to finish, then retry.</comment>');
            return Command::FAILURE;
        } catch (\Throwable $e) {
            $output->writeln('<error>' . $e->getMessage() . '</error>');
            return Command::FAILURE;
        }

        if ($failures !== []) {
            foreach ($failures as $failure) {
                $output->writeln('<error>' . $failure . '</error>');
            }
            return Command::FAILURE;
        }

        $output->writeln('<info>Done.</info>');
        return Command::SUCCESS;
    }

    /**
     * Whether the group is a feed group, or a sitemap group for a type the generator writes.
     *
     * @param string $group
     * @return bool
     */
    private function isKnown(string $group): bool
    {
        $sitemapType = $this->rebuildGroup->typeOf($group);

        return $sitemapType === null
            ? \in_array($group, FeedRegenerator::GROUPS, true)
            : $this->sitemapRebuilder->hasType($sitemapType);
    }

    /**
     * Every group the command takes.
     *
     * @return string[]
     */
    private function knownGroups(): array
    {
        return [
            ...FeedRegenerator::GROUPS,
            ...array_map([$this->rebuildGroup, 'forType'], $this->sitemapRebuilder->types()),
            $this->rebuildGroup->forType(RebuildGroup::ALL_TYPES),
        ];
    }

    /**
     * Set the global area, as the queue consumer does, unless an area is already set.
     *
     * Not State::emulateAreaCode(): while an area is emulated, the theme design model resolves
     * themes against the emulated area instead of the frontend area the store emulation sets,
     * and loading the store's theme translations fails ("Required parameter 'theme_dir' was
     * not passed").
     *
     * @throws LocalizedException
     * @return void
     */
    private function ensureAreaCode(): void
    {
        try {
            $this->appState->getAreaCode();
        } catch (LocalizedException) {
            $this->appState->setAreaCode(Area::AREA_GLOBAL);
        }
    }
}
