<?php

declare(strict_types=1);

namespace MageOS\Seo\Console\Command;

use Magento\Framework\App\Area;
use Magento\Framework\App\State;
use Magento\Framework\Exception\LocalizedException;
use MageOS\Seo\Exception\RebuildInProgressException;
use MageOS\Seo\Model\Rebuild\HandlerPool;
use MageOS\Seo\Model\Rebuild\ProblemLog;
use MageOS\Seo\Model\Sitemap\RebuildableSitemaps;
use MageOS\Seo\Model\Sitemap\Rebuilder as SitemapRebuilder;
use MageOS\Seo\Model\Sitemap\RebuildGroup;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Rebuilds the pre-generated feeds immediately, in this process — or, asked by group, one type
 * of page in the XML sitemaps this module generates.
 *
 * The feeds are the groups other modules register with the rebuild queue (Model\Rebuild\HandlerPool)
 * — the llms documents, for example. The manual counterpart of the nightly cron and the queue: for
 * deployment scripts that need the feeds in place before traffic arrives, and for rebuilding on
 * demand — a sitemap type after a change the rebuild-on-change triggers cannot see, such as an import
 * written straight to the database. It does not need the queue consumer to be running. With no group
 * it rebuilds the feeds only: a sitemap is rebuilt when a `sitemap-…` group is named.
 */
class RegenerateFeedsCommand extends Command
{
    private const OPTION_GROUP = 'group';

    /**
     * @param HandlerPool $handlerPool Injected as a proxy: its handlers are built only when the command runs
     * @param State $appState
     * @param SitemapRebuilder $sitemapRebuilder Injected as a proxy, for the same reason
     * @param RebuildableSitemaps $rebuildableSitemaps
     * @param RebuildGroup $rebuildGroup
     * @param ProblemLog $problemLog Injected as a proxy, for the same reason
     * @param string|null $name
     */
    public function __construct(
        private readonly HandlerPool         $handlerPool,
        private readonly State               $appState,
        private readonly SitemapRebuilder    $sitemapRebuilder,
        private readonly RebuildableSitemaps $rebuildableSitemaps,
        private readonly RebuildGroup        $rebuildGroup,
        private readonly ProblemLog          $problemLog,
        ?string $name = null
    ) {
        parent::__construct($name);
    }

    /**
     * Name, description and option; nothing here may touch the handler pool.
     *
     * Every command is configured when bin/magento starts — setup:install included, before any store
     * exists — and the pool's handlers read store configuration. The feed groups are listed by
     * getHelp(), which runs only when this command's help is asked for.
     *
     * @inheritDoc
     */
    protected function configure(): void
    {
        $this->setName('seo:rebuild')
            ->setDescription(
                'Rebuild the pre-generated feeds for every active store view, or a type of page in the XML sitemaps'
            )
            ->addOption(
                self::OPTION_GROUP,
                'g',
                InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY,
                'Group to rebuild: a feed group (listed below); '
                . RebuildGroup::PREFIX . 'TYPE for one type of page in every sitemap generated by MageOS SEO'
                . ' (' . RebuildGroup::PREFIX . 'pages, ' . RebuildGroup::PREFIX . 'products, or another'
                . ' module\'s type); \'' . RebuildGroup::PREFIX . RebuildGroup::ALL_TYPES . '\' for every type;'
                . ' or ' . RebuildGroup::MISSING . ' for the first build of the sitemaps that have no file yet.'
                . ' Repeat for several. Default: every feed, no sitemap'
            );

        parent::configure();
    }

    /**
     * The command's help, with the feed groups the installed modules register.
     *
     * @return string
     */
    public function getHelp(): string
    {
        $groups = $this->handlerPool->getGroups();

        return trim(parent::getHelp() . "\n\nFeed groups: " . ($groups === [] ? 'none' : implode(', ', $groups)) . '.');
    }

    /**
     * @inheritDoc
     */
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $groups  = array_values(array_unique(array_map('strval', (array) $input->getOption(self::OPTION_GROUP))));
        $unknown = array_values(array_filter($groups, fn (string $group): bool => !$this->isKnown($group)));
        if ($unknown !== []) {
            $output->writeln(\sprintf(
                '<error>Unknown feed group(s): %s. Use: %s.</error>',
                implode(', ', $unknown),
                implode(', ', $this->knownGroups())
            ));
            return Command::INVALID;
        }

        // Sitemaps are rebuilt from here only when asked for, so without a registered feed group
        // (MageOS_Seo on its own) a plain run has nothing to do. Saying so beats a silent "Done.".
        if ($groups === [] && $this->handlerPool->getGroups() === []) {
            $output->writeln(\sprintf(
                '<comment>Nothing to rebuild: no feed group is registered. Rebuild the sitemaps with'
                . ' -g %sTYPE, or -g \'%s%s\' for every type.</comment>',
                RebuildGroup::PREFIX,
                RebuildGroup::PREFIX,
                RebuildGroup::ALL_TYPES
            ));
            return Command::SUCCESS;
        }

        $failures = [];
        try {
            $this->ensureAreaCode();
            foreach ($groups === [] ? [null] : $groups as $group) {
                $label = $group ?? 'all feeds';
                $output->writeln(\sprintf('Rebuilding %s...', $label));

                if ($group === RebuildGroup::MISSING) {
                    // The queue's first-build group, named so the admin's rebuild message can give
                    // a command for every group it lists.
                    $result = $this->recorded($group, fn (): array => $this->sitemapRebuilder->buildMissing());
                    foreach ($result as $sitemapId => $message) {
                        $failures[] = \sprintf('%s, sitemap %d: %s', $label, $sitemapId, $message);
                    }
                    continue;
                }

                $sitemapType = $group === null ? null : $this->rebuildGroup->typeOf($group);
                if ($sitemapType === null) {
                    $handlers = $group === null
                        ? $this->handlerPool->getHandlers()
                        : array_filter([$this->handlerPool->get($group)]);
                    foreach ($handlers as $handler) {
                        $result = $this->recorded($group, fn (): array => $handler->rebuild($group));
                        foreach ($result as $storeId => $message) {
                            $failures[] = \sprintf('%s, store view %d: %s', $label, $storeId, $message);
                        }
                    }
                    continue;
                }

                if ($this->rebuildableSitemaps->all() === []) {
                    $output->writeln(
                        '<comment>No sitemap to rebuild: no Site Map entry is on an active store view'
                        . ' that uses the MageOS SEO generator. Add one under Marketing → Site Map.</comment>'
                    );
                    continue;
                }
                $result = $this->recorded(
                    $group,
                    fn (): array => $this->sitemapRebuilder->rebuildOnDemand($sitemapType)
                );
                foreach ($result as $sitemapId => $message) {
                    $failures[] = \sprintf('%s, sitemap %d: %s', $label, $sitemapId, $message);
                }
            }
        } catch (RebuildInProgressException $e) {
            // Distinguished from a crash for the operator's sake — nothing is broken, the cron or
            // the queue consumer is mid-rebuild. Still a failure: the files asked for were not
            // written, and a deployment script must not read this as "done".
            $output->writeln('<error>' . $e->getMessage() . '</error>');
            $output->writeln('<comment>Wait for the running rebuild to finish, then retry.</comment>');
            return Command::FAILURE;
        } catch (\Throwable $e) {
            $output->writeln('<error>' . $e->getMessage() . '</error>');
            return Command::FAILURE;
        }

        if ($failures !== []) {
            foreach ($failures as $failure) {
                $output->writeln('<error>' . $failure . '</error>');
            }
            return Command::FAILURE;
        }

        $output->writeln('<info>Done.</info>');
        return Command::SUCCESS;
    }

    /**
     * Whether the command takes the group.
     *
     * A feed group, a sitemap group for a type the generator writes, or the sitemaps' first build.
     *
     * @param string $group
     * @return bool
     */
    private function isKnown(string $group): bool
    {
        if ($group === RebuildGroup::MISSING) {
            return true;
        }
        $sitemapType = $this->rebuildGroup->typeOf($group);

        return $sitemapType === null
            ? $this->handlerPool->get($group) !== null
            : $this->sitemapRebuilder->hasType($sitemapType);
    }

    /**
     * Every group the command takes.
     *
     * @return string[]
     */
    private function knownGroups(): array
    {
        return [
            ...$this->handlerPool->getGroups(),
            ...array_map([$this->rebuildGroup, 'forType'], $this->sitemapRebuilder->types()),
            $this->rebuildGroup->forType(RebuildGroup::ALL_TYPES),
            RebuildGroup::MISSING,
        ];
    }

    /**
     * Set the global area, as the queue consumer does, unless an area is already set.
     *
     * Not State::emulateAreaCode(): while an area is emulated, the theme design model resolves
     * themes against the emulated area instead of the frontend area the store emulation sets,
     * and loading the store's theme translations fails ("Required parameter 'theme_dir' was
     * not passed").
     *
     * @throws LocalizedException
     * @return void
     */
    private function ensureAreaCode(): void
    {
        try {
            $this->appState->getAreaCode();
        } catch (LocalizedException) {
            $this->appState->setAreaCode(Area::AREA_GLOBAL);
        }
    }

    /**
     * Run one group's rebuild and record what it found as the group's problems in the admin.
     *
     * So a successful run by hand clears them (see ProblemLog). A run of every group (no -g) is not
     * recorded here: its results are not per group. Handlers record their own, as MageOS_Aeo's does.
     *
     * @param string|null $group
     * @param callable():array<int|string,string> $rebuild
     * @throws \Throwable What the rebuild threw
     * @return array<int|string, string> Error message per store view or sitemap ID that failed
     */
    private function recorded(?string $group, callable $rebuild): array
    {
        if ($group === null) {
            return $rebuild();
        }

        $this->problemLog->rebuilding($group);
        try {
            $failures = $rebuild();
        } catch (RebuildInProgressException $e) {
            $this->problemLog->abandoned($group);
            throw $e;
        } catch (\Throwable $e) {
            $this->problemLog->rebuilt($group, [ProblemLog::ALL => $e->getMessage()]);
            throw $e;
        }
        $this->problemLog->rebuilt($group, $failures);

        return $failures;
    }
}
